"""
tests/test_coverage_common.py
==============================
Unit / example-based tests for scripts/coverage_common.py pure helpers:

  assign_work(n_queries, task_id, n_tasks) -> list[int]
  merge_shards(shard_list)                 -> list[list]
  rows_to_matrix(rows, query_labels)       -> tuple[list, list, dict]

These tests use concrete, fixed inputs to verify exact expected outputs.
Property-based tests are in test_coverage_common_generated.py (autogenerated
via ``axiomander gen-tests``).
Contract / negative tests are in test_coverage_common_axiomander.py.
"""

import os
import sys

import pytest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "scripts"))

from coverage_common import assign_work, merge_shards, rows_to_matrix


# ---------------------------------------------------------------------------
# assign_work
# ---------------------------------------------------------------------------


class TestAssignWork:
    """Concrete examples for assign_work."""

    def test_single_task_gets_all_queries(self):
        """With n_tasks=1, task 0 gets every query index."""
        result = assign_work(5, 0, 1)
        assert result == [0, 1, 2, 3, 4]

    def test_two_tasks_even_split(self):
        """With n_tasks=2 and 4 queries, each task gets 2 indices."""
        assert assign_work(4, 0, 2) == [0, 2]
        assert assign_work(4, 1, 2) == [1, 3]

    def test_two_tasks_odd_queries(self):
        """With n_tasks=2 and 5 queries, task 0 gets 3, task 1 gets 2."""
        assert assign_work(5, 0, 2) == [0, 2, 4]
        assert assign_work(5, 1, 2) == [1, 3]

    def test_three_tasks_round_robin(self):
        """Round-robin partition across 3 tasks."""
        assert assign_work(9, 0, 3) == [0, 3, 6]
        assert assign_work(9, 1, 3) == [1, 4, 7]
        assert assign_work(9, 2, 3) == [2, 5, 8]

    def test_zero_queries_returns_empty(self):
        """Zero queries → every task gets an empty list."""
        assert assign_work(0, 0, 1) == []
        assert assign_work(0, 0, 3) == []

    def test_task_id_beyond_n_queries_returns_empty(self):
        """task_id >= n_queries → empty list (no work to do)."""
        assert assign_work(2, 2, 5) == []
        assert assign_work(2, 4, 5) == []

    def test_partition_covers_all_indices(self):
        """Union of all tasks' indices == range(n_queries)."""
        n_queries, n_tasks = 13, 4
        all_indices = []
        for t in range(n_tasks):
            all_indices.extend(assign_work(n_queries, t, n_tasks))
        assert sorted(all_indices) == list(range(n_queries))

    def test_partition_is_disjoint(self):
        """No index appears in more than one task's list."""
        n_queries, n_tasks = 11, 3
        seen = set()
        for t in range(n_tasks):
            indices = assign_work(n_queries, t, n_tasks)
            for i in indices:
                assert i not in seen, f"Index {i} assigned to multiple tasks"
                seen.add(i)

    def test_n_tasks_equals_n_queries(self):
        """When n_tasks == n_queries, each task gets exactly one index."""
        n = 5
        for t in range(n):
            assert assign_work(n, t, n) == [t]

    def test_large_n_tasks_relative_to_queries(self):
        """When n_tasks > n_queries, some tasks get empty lists."""
        result_0 = assign_work(3, 0, 10)
        result_5 = assign_work(3, 5, 10)
        assert result_0 == [0]
        assert result_5 == []


# ---------------------------------------------------------------------------
# merge_shards
# ---------------------------------------------------------------------------


class TestMergeShards:
    """Concrete examples for merge_shards."""

    def test_empty_shard_list(self):
        """Empty input → empty output."""
        assert merge_shards([]) == []

    def test_single_shard_passthrough(self):
        """Single shard with no duplicates is returned as-is."""
        shard = [
            ["tf1", "cand1", "out1", True],
            ["tf1", "cand2", "out1", False],
        ]
        result = merge_shards([shard])
        assert len(result) == 2
        assert result[0] == ["tf1", "cand1", "out1", True]
        assert result[1] == ["tf1", "cand2", "out1", False]

    def test_two_disjoint_shards_merged(self):
        """Two shards with no overlapping keys are fully merged."""
        shard_a = [["tf1", "cand1", "out1", True]]
        shard_b = [["tf1", "cand2", "out1", False]]
        result = merge_shards([shard_a, shard_b])
        assert len(result) == 2

    def test_duplicate_key_first_wins(self):
        """When two shards share a key, the first occurrence wins."""
        shard_a = [["tf1", "cand1", "out1", True]]
        shard_b = [["tf1", "cand1", "out1", False]]  # same key, different value
        result = merge_shards([shard_a, shard_b])
        assert len(result) == 1
        assert result[0][3] is True  # first shard's value kept

    def test_all_duplicates_collapses_to_one(self):
        """Three shards all containing the same row → one row in output."""
        row = ["tf1", "cand1", "out1", True]
        result = merge_shards([[row], [row], [row]])
        assert len(result) == 1

    def test_output_rows_are_lists(self):
        """Output rows are always lists (even if input rows were tuples)."""
        shard = [("tf1", "cand1", "out1", True)]
        result = merge_shards([shard])
        assert isinstance(result[0], list)

    def test_no_duplicate_keys_in_output(self):
        """Output never has duplicate (tf1, candidate, outcome) keys."""
        shards = [
            [["A", "B", "C", True], ["A", "D", "C", False]],
            [["A", "B", "C", False], ["A", "E", "C", True]],  # A,B,C is dup
        ]
        result = merge_shards(shards)
        keys = [(r[0], r[1], r[2]) for r in result]
        assert len(keys) == len(set(keys))

    def test_all_rows_have_four_elements(self):
        """Every row in the output has exactly 4 elements."""
        shards = [
            [["tf1", "c1", "o1", True], ["tf1", "c2", "o1", False]],
            [["tf2", "c1", "o2", True]],
        ]
        result = merge_shards(shards)
        assert all(len(r) == 4 for r in result)

    def test_empty_shards_within_list(self):
        """Empty shards within the list are silently skipped."""
        result = merge_shards([[], [["tf1", "c1", "o1", True]], []])
        assert len(result) == 1


# ---------------------------------------------------------------------------
# rows_to_matrix
# ---------------------------------------------------------------------------


class TestRowsToMatrix:
    """Concrete examples for rows_to_matrix."""

    def test_empty_rows(self):
        """Empty rows → empty candidate_set and empty lookup."""
        candidate_set, labels_out, lookup = rows_to_matrix([], ["tf1->out1"])
        assert candidate_set == []
        assert lookup == {}

    def test_single_row(self):
        """Single row produces one candidate and one lookup entry."""
        rows = [["tf1", "cand1", "out1", True]]
        candidate_set, labels_out, lookup = rows_to_matrix(rows, ["tf1->out1"])
        assert candidate_set == ["cand1"]
        assert lookup[("cand1", "tf1->out1")] is True

    def test_candidate_set_is_sorted(self):
        """candidate_set is always sorted alphabetically."""
        rows = [
            ["tf1", "zebra", "out1", True],
            ["tf1", "alpha", "out1", False],
            ["tf1", "mango", "out1", True],
        ]
        candidate_set, _, _ = rows_to_matrix(rows, ["tf1->out1"])
        assert candidate_set == sorted(candidate_set)
        assert candidate_set == ["alpha", "mango", "zebra"]

    def test_lookup_key_format(self):
        """Lookup keys are (candidate, 'tf1->outcome') strings."""
        rows = [["tf1", "cand1", "out1", False]]
        _, _, lookup = rows_to_matrix(rows, ["tf1->out1"])
        assert ("cand1", "tf1->out1") in lookup
        assert lookup[("cand1", "tf1->out1")] is False

    def test_multiple_queries_multiple_candidates(self):
        """Matrix with 2 queries × 2 candidates has 4 lookup entries."""
        rows = [
            ["tf1", "cand1", "out1", True],
            ["tf1", "cand2", "out1", False],
            ["tf2", "cand1", "out2", False],
            ["tf2", "cand2", "out2", True],
        ]
        labels = ["tf1->out1", "tf2->out2"]
        candidate_set, labels_out, lookup = rows_to_matrix(rows, labels)
        assert set(candidate_set) == {"cand1", "cand2"}
        assert lookup[("cand1", "tf1->out1")] is True
        assert lookup[("cand2", "tf1->out1")] is False
        assert lookup[("cand1", "tf2->out2")] is False
        assert lookup[("cand2", "tf2->out2")] is True

    def test_query_labels_passed_through(self):
        """The second element of the return tuple is the input query_labels."""
        labels = ["tf1->out1", "tf2->out2"]
        rows = [["tf1", "cand1", "out1", True]]
        _, labels_out, _ = rows_to_matrix(rows, labels)
        assert labels_out is labels  # same object

    def test_found_values_are_bool(self):
        """Lookup values are booleans."""
        rows = [["tf1", "cand1", "out1", 1]]  # int 1 → bool True
        _, _, lookup = rows_to_matrix(rows, ["tf1->out1"])
        val = lookup[("cand1", "tf1->out1")]
        assert isinstance(val, bool)
        assert val is True

    def test_return_is_three_tuple(self):
        """Return value is a 3-tuple."""
        result = rows_to_matrix([], [])
        assert isinstance(result, tuple)
        assert len(result) == 3
